// This file is generated by shader-compiler. Do not manually edit this file.

#pragma once

#include <stddef.h>
#include <stdint.h>

extern uint8_t const AADF_GLOBAL_CS_BYTES[];
extern size_t const AADF_GLOBAL_CS_SIZE;

extern uint8_t const AADF_LOCAL_CS_BYTES[];
extern size_t const AADF_LOCAL_CS_SIZE;

extern uint8_t const DISPLAY_PS_BYTES[];
extern size_t const DISPLAY_PS_SIZE;

extern uint8_t const FULLSCREEN_VS_BYTES[];
extern size_t const FULLSCREEN_VS_SIZE;

extern uint8_t const GBUFFER_PS_BYTES[];
extern size_t const GBUFFER_PS_SIZE;

extern uint8_t const RTAO_INDEX_PS_BYTES[];
extern size_t const RTAO_INDEX_PS_SIZE;

extern uint8_t const RTAO_PS_BYTES[];
extern size_t const RTAO_PS_SIZE;
