// This file is generated by shader-compiler. Do not manually edit this file.

#pragma once

#include <stddef.h>
#include <stdint.h>

extern uint8_t const DDA_PS_BYTES[];
extern size_t const DDA_PS_SIZE;

extern uint8_t const DDA_VS_BYTES[];
extern size_t const DDA_VS_SIZE;
